[tool.poetry]
name = "agnos"
version = "0.1.0"
authors = ["Vehicle Researcher <user@comma.ai>"]
description = ""

[tool.poetry.dependencies]
python = "~3.11"
atomicwrites = "*"
cffi = "*"
crcmod = "*"
hexdump = "*"
libusb1 = "*"
numpy = "==1.24.2"  # can be unpinned once acados is updated
psutil = "*"
pycapnp = "*"
cryptography = "*"
python-dateutil = "*"
pyzmq = "*"
requests = "*"
setproctitle = "*"
six = "*"
smbus2 = "*"
sympy = "!=1.6.1"
tqdm = "*"
Cython = "*"
PyYAML = "*"
websocket_client = "*"
urllib3 = "*"
gunicorn = "*"
utm = "*"
json-rpc = "*"
Flask = "*"
nose = "*"
flake8 = "*"
pylint = "*"
pillow = "*"
scons = "*"
sconscontrib = {git = "https://github.com/SCons/scons-contrib"}
pycryptodome = "*"
Jinja2 = "*"
PyJWT = "*"
pyserial = "*"
dbus-python = "*"
timezonefinder = "*"
sentry-sdk = "*"
markdown-it-py = "*"
onnx = "*"
onnxruntime = "*"
pyopencl = "*"
pytest = "*"
hatanaka = "==2.4"
protobuf = "*"
torch = "*"
spidev = "*"
spidev2 = "*"
sounddevice = "*"
zstandard = "*"
zstd = "*"
pyzstd = "*"
casadi = "*"
pyaudio = "*"
pydub = "*"
aiohttp = "*"
aiortc = "*"
evdev = "*"
pytest-random-order = "^1.1.0"

[tool.poetry.group.dev.dependencies]
ipython = "*"
azure-core = "*"
azure-common = "*"
azure-storage-blob = "~=2.1"
azure-storage-common = "~=2.1"
pycurl = "*"
git-pylint-commit-hook = "*"
tenacity = "*"
mock = "*"
dictdiffer = "*"
aenum = "*"
coverage = "*"
paramiko = "*"
lru-dict = "*"
pprofile = "*"
pyprof2calltree = "*"
pre-commit = "*"
mypy = "*"
parameterized = "*"
inputs = "*"
future-fstrings = "*"
tabulate = "*"
flaky = "*"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
pytest-mock = "*"
pytest-repeat = "*"
pytest-timeout = "*"
pytest-timeouts = "*"
hypothesis = "*"
